import './globals.css'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import clsx from 'clsx'

const ApercuBold = localFont({
  src: '../public/Apercu_Bold.otf',
  display: 'swap',
  variable: '--apercu-bold',
})

const ApercuLight = localFont({
    src: '../public/Apercu_Light.otf',
    display: 'swap',
    variable: '--apercu-light',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(ApercuBold.variable, ApercuLight.variable, 'bg-gray-800')}>{children}</body>
    </html>
  )
}
